@isTest
private class HideAndShow_Test{
   static testMethod void test_showA_UseCase1(){
    HideAndShow obj01 = new HideAndShow();
    obj01.abool = false;
    obj01.bbool = false;
    obj01.sabool = false;
    obj01.sbbool = false;
    obj01.habool = false;
    obj01.hbbool = false;
    obj01.sabbool = false;
    obj01.habbool = false;
    obj01.showA();
  }
   static testMethod void test_showB_UseCase1(){
    HideAndShow obj01 = new HideAndShow();
    obj01.abool = false;
    obj01.bbool = false;
    obj01.sabool = false;
    obj01.sbbool = false;
    obj01.habool = false;
    obj01.hbbool = false;
    obj01.sabbool = false;
    obj01.habbool = false;
    obj01.showB();
  }
   static testMethod void test_hideA_UseCase1(){
    HideAndShow obj01 = new HideAndShow();
    obj01.abool = false;
    obj01.bbool = false;
    obj01.sabool = false;
    obj01.sbbool = false;
    obj01.habool = false;
    obj01.hbbool = false;
    obj01.sabbool = false;
    obj01.habbool = false;
    obj01.hideA();
  }
   static testMethod void test_hideB_UseCase1(){
    HideAndShow obj01 = new HideAndShow();
    obj01.abool = false;
    obj01.bbool = false;
    obj01.sabool = false;
    obj01.sbbool = false;
    obj01.habool = false;
    obj01.hbbool = false;
    obj01.sabbool = false;
    obj01.habbool = false;
    obj01.hideB();
  }
   static testMethod void test_showAB_UseCase1(){
    HideAndShow obj01 = new HideAndShow();
    obj01.abool = false;
    obj01.bbool = false;
    obj01.sabool = false;
    obj01.sbbool = false;
    obj01.habool = false;
    obj01.hbbool = false;
    obj01.sabbool = false;
    obj01.habbool = false;
    obj01.showAB();
  }
   static testMethod void test_hideAB_UseCase1(){
    HideAndShow obj01 = new HideAndShow();
    obj01.abool = false;
    obj01.bbool = false;
    obj01.sabool = false;
    obj01.sbbool = false;
    obj01.habool = false;
    obj01.hbbool = false;
    obj01.sabbool = false;
    obj01.habbool = false;
    obj01.hideAB();
  }
   static testMethod void test_check_UseCase1(){
    HideAndShow obj01 = new HideAndShow();
    obj01.abool = false;
    obj01.bbool = false;
    obj01.sabool = false;
    obj01.sbbool = false;
    obj01.habool = false;
    obj01.hbbool = false;
    obj01.sabbool = false;
    obj01.habbool = false;
    obj01.check();
  }
}