@isTest
public class UnitTestClassGenerator_UT {

    static testMethod void writeCode_UT() {
        UnitTestClassGenerator localobj = new UnitTestClassGenerator();
        String ClassName = 'hello';
        String FunctionName = 'hello';
        String Code = 'hello';
        Test.startTest();
              //  localobj.writeCode(ClassName,FunctionName,Code);
                Test.stopTest();

        //To-Verify
        System.AssertEquals(true,false);
        //To-Verify
}                   
     }